QUIZZES = {
    "10-12": {
        "titulo": "Desafio 1",
        "faixa_label": "10 a 12 anos",
        "emoji": "🟢",
        "cor": "verde",
        "perguntas": [
            {
                "id": 1,
                "enunciado": "Quantos rins uma pessoa geralmente possui?",
                "opcoes": {"A": "1", "B": "2", "C": "3", "D": "4"},
                "correta": "B",
            },
            {
                "id": 2,
                "enunciado": "Qual é a principal função dos rins?",
                "opcoes": {
                    "A": "Filtrar o sangue e ajudar a produzir a urina",
                    "B": "Bombear o sangue",
                    "C": "Fazer a digestão dos alimentos",
                    "D": "Produzir o ar que respiramos",
                },
                "correta": "A",
            },
            {
                "id": 3,
                "enunciado": "Onde a urina fica armazenada antes de ser eliminada?",
                "opcoes": {"A": "Nos rins", "B": "Nos ureteres", "C": "Na bexiga", "D": "No estômago"},
                "correta": "C",
            },
            {
                "id": 4,
                "enunciado": "Qual estrutura leva a urina dos rins até a bexiga?",
                "opcoes": {"A": "Uretra", "B": "Ureter", "C": "Intestino", "D": "Pulmão"},
                "correta": "B",
            },
            {
                "id": 5,
                "enunciado": "Qual estrutura leva a urina da bexiga para fora do corpo?",
                "opcoes": {"A": "Ureter", "B": "Rim", "C": "Uretra", "D": "Néfron"},
                "correta": "C",
            },
            {
                "id": 6,
                "enunciado": "Qual destas atitudes ajuda a cuidar do sistema urinário?",
                "opcoes": {
                    "A": "Beber água adequadamente",
                    "B": "Nunca beber água",
                    "C": "Segurar a urina sempre que possível",
                    "D": "Substituir água por refrigerante",
                },
                "correta": "A",
            },
            {
                "id": 7,
                "enunciado": "Qual destes órgãos NÃO faz parte do sistema urinário?",
                "opcoes": {"A": "Rim", "B": "Bexiga", "C": "Ureter", "D": "Coração"},
                "correta": "D",
            },
            {
                "id": 8,
                "enunciado": "Qual é a sequência correta do caminho da urina?",
                "opcoes": {
                    "A": "Rins → ureteres → bexiga → uretra",
                    "B": "Bexiga → rins → uretra → ureteres",
                    "C": "Uretra → rins → bexiga → ureteres",
                    "D": "Rins → bexiga → ureteres → uretra",
                },
                "correta": "A",
            },
        ],
    },
    "13-15": {
        "titulo": "Desafio 2",
        "faixa_label": "13 a 15 anos",
        "emoji": "🟡",
        "cor": "amarelo",
        "perguntas": [
            {
                "id": 1,
                "enunciado": "Além de formar a urina, os rins ajudam o organismo principalmente a:",
                "opcoes": {
                    "A": "Controlar os movimentos dos músculos",
                    "B": "Manter o equilíbrio de água e sais minerais",
                    "C": "Produzir o alimento utilizado pelas células",
                    "D": "Realizar a digestão dos alimentos",
                },
                "correta": "B",
            },
            {
                "id": 2,
                "enunciado": "Qual é a ordem correta das estruturas por onde passa a urina?",
                "opcoes": {
                    "A": "Rins → uretra → bexiga → ureteres",
                    "B": "Rins → ureteres → bexiga → uretra",
                    "C": "Bexiga → ureteres → rins → uretra",
                    "D": "Ureteres → rins → bexiga → uretra",
                },
                "correta": "B",
            },
            {
                "id": 3,
                "enunciado": "O que são os néfrons?",
                "opcoes": {
                    "A": "Estruturas funcionais dos rins envolvidas na formação da urina",
                    "B": "Tubos que levam a urina da bexiga para fora do corpo",
                    "C": "Músculos responsáveis por movimentar os rins",
                    "D": "Órgãos que armazenam a urina",
                },
                "correta": "A",
            },
            {
                "id": 4,
                "enunciado": "Por que a urina contém substâncias que o organismo precisa eliminar?",
                "opcoes": {
                    "A": "Porque os rins retiram determinados resíduos do sangue",
                    "B": "Porque a bexiga transforma alimentos em resíduos",
                    "C": "Porque os ureteres produzem substâncias tóxicas",
                    "D": "Porque a uretra filtra o sangue",
                },
                "correta": "A",
            },
            {
                "id": 5,
                "enunciado": "Qual é a função dos ureteres?",
                "opcoes": {
                    "A": "Filtrar o sangue",
                    "B": "Armazenar a urina",
                    "C": "Transportar a urina dos rins até a bexiga",
                    "D": "Levar a urina da bexiga para fora do corpo",
                },
                "correta": "C",
            },
            {
                "id": 6,
                "enunciado": "Qual afirmação sobre a bexiga urinária está correta?",
                "opcoes": {
                    "A": "É responsável pela filtragem do sangue",
                    "B": "Armazena temporariamente a urina",
                    "C": "Produz a maior parte da urina",
                    "D": "Liga diretamente os rins ao sangue",
                },
                "correta": "B",
            },
            {
                "id": 7,
                "enunciado": "Por que beber água é importante para o funcionamento do organismo e do sistema urinário?",
                "opcoes": {
                    "A": "Porque a água substitui completamente a função dos rins",
                    "B": "Porque participa de processos do organismo e da formação da urina",
                    "C": "Porque impede que o sangue chegue aos rins",
                    "D": "Porque faz a bexiga produzir sangue",
                },
                "correta": "B",
            },
            {
                "id": 8,
                "enunciado": "Qual alternativa apresenta somente estruturas do sistema urinário?",
                "opcoes": {
                    "A": "Rins, ureteres, bexiga e uretra",
                    "B": "Rins, pulmões, bexiga e coração",
                    "C": "Estômago, ureteres, rins e fígado",
                    "D": "Coração, uretra, bexiga e pulmões",
                },
                "correta": "A",
            },
        ],
    },
    "16-17": {
        "titulo": "Desafio 3",
        "faixa_label": "16 a 17 anos",
        "emoji": "🔴",
        "cor": "vermelho",
        "perguntas": [
            {
                "id": 1,
                "enunciado": "Qual alternativa melhor descreve uma das funções dos rins?",
                "opcoes": {
                    "A": "Filtrar o sangue e contribuir para o equilíbrio de água e sais do organismo",
                    "B": "Armazenar permanentemente a urina produzida pelo organismo",
                    "C": "Transportar a urina diretamente para fora do corpo",
                    "D": "Produzir células sanguíneas em todas as fases da vida",
                },
                "correta": "A",
            },
            {
                "id": 2,
                "enunciado": "Uma pessoa apresenta o seguinte caminho da urina: rins → X → bexiga → uretra. O que deve ocupar o lugar de X?",
                "opcoes": {"A": "Ureteres", "B": "Néfrons", "C": "Alvéolos", "D": "Intestinos"},
                "correta": "A",
            },
            {
                "id": 3,
                "enunciado": "Qual é a relação correta entre néfrons e rins?",
                "opcoes": {
                    "A": "Os néfrons são estruturas funcionais dos rins que participam da formação da urina",
                    "B": "Os néfrons são órgãos externos que armazenam a urina",
                    "C": "Os néfrons transportam a urina da bexiga para fora do corpo",
                    "D": "Os néfrons são músculos localizados ao redor da uretra",
                },
                "correta": "A",
            },
            {
                "id": 4,
                "enunciado": "A formação da urina está diretamente relacionada a qual processo?",
                "opcoes": {
                    "A": "Filtragem e processamento de substâncias presentes no sangue nos rins",
                    "B": "Armazenamento dos alimentos no estômago",
                    "C": "Troca de gases realizada pelos pulmões",
                    "D": "Contração dos músculos responsáveis pelos movimentos corporais",
                },
                "correta": "A",
            },
            {
                "id": 5,
                "enunciado": "Qual alternativa diferencia corretamente ureter e uretra?",
                "opcoes": {
                    "A": "O ureter leva urina dos rins à bexiga; a uretra conduz a urina para fora do corpo",
                    "B": "O ureter armazena urina; a uretra filtra o sangue",
                    "C": "O ureter leva sangue aos rins; a uretra produz urina",
                    "D": "O ureter e a uretra possuem exatamente a mesma função",
                },
                "correta": "A",
            },
            {
                "id": 6,
                "enunciado": "Qual situação representa melhor uma função de regulação realizada pelos rins?",
                "opcoes": {
                    "A": "Ajudar a controlar a quantidade de água e sais minerais eliminados na urina",
                    "B": "Armazenar todos os nutrientes ingeridos durante uma refeição",
                    "C": "Realizar a troca de oxigênio e gás carbônico",
                    "D": "Produzir a bile utilizada na digestão",
                },
                "correta": "A",
            },
            {
                "id": 7,
                "enunciado": "Por que a bexiga não pode ser considerada o órgão responsável pela formação da urina?",
                "opcoes": {
                    "A": "Porque ela principalmente armazena a urina, enquanto sua formação ocorre nos rins",
                    "B": "Porque ela pertence ao sistema respiratório",
                    "C": "Porque ela transporta o sangue para os rins",
                    "D": "Porque ela produz os néfrons",
                },
                "correta": "A",
            },
            {
                "id": 8,
                "enunciado": "Imagine que uma pessoa tenha uma alteração que impeça os ureteres de transportar corretamente a urina. Qual etapa do caminho urinário seria diretamente prejudicada?",
                "opcoes": {
                    "A": "A passagem da urina dos rins para a bexiga",
                    "B": "A filtragem inicial do sangue pelos pulmões",
                    "C": "A passagem do ar pela traqueia",
                    "D": "A digestão dos alimentos no estômago",
                },
                "correta": "A",
            },
        ],
    },
}
